### ISSUE TITLE
Ubuntu packages

### ISSUE THREAD

**Issue by kylerlaird** [wunderkammer-laboratory/ackermann_vehicle#3]
[I'm new to ROS and still learning the basics.]

What is the relationship between the code in this git repository and the Ubuntu ros-indigo-ackermann-vehicle* packages?  It appears that the Ubuntu packages contain only package descriptions and cmake files  - no URDF file, for example.  Is there some magic I'm missing?

Are there any examples/tutorials for using this code?

Thank you.

--kyler

$ for pkg in `dpkg -l |grep ros-indigo-ackermann-vehicle |cut -c5-55`; do echo '===========' $pkg; dpkg -L $pkg; done
=========== ros-indigo-ackermann-vehicle
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/ros-indigo-ackermann-vehicle
/usr/share/doc/ros-indigo-ackermann-vehicle/changelog.Debian.gz
/opt
/opt/ros
/opt/ros/indigo
/opt/ros/indigo/share
/opt/ros/indigo/share/ackermann_vehicle
/opt/ros/indigo/share/ackermann_vehicle/package.xml
=========== ros-indigo-ackermann-vehicle-description
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/ros-indigo-ackermann-vehicle-description
/usr/share/doc/ros-indigo-ackermann-vehicle-description/changelog.Debian.gz
/opt
/opt/ros
/opt/ros/indigo
/opt/ros/indigo/share
/opt/ros/indigo/share/ackermann_vehicle_description
/opt/ros/indigo/share/ackermann_vehicle_description/package.xml
/opt/ros/indigo/share/ackermann_vehicle_description/cmake
/opt/ros/indigo/share/ackermann_vehicle_description/cmake/ackermann_vehicle_descriptionConfig-version.cmake
/opt/ros/indigo/share/ackermann_vehicle_description/cmake/ackermann_vehicle_descriptionConfig.cmake
/opt/ros/indigo/lib
/opt/ros/indigo/lib/pkgconfig
/opt/ros/indigo/lib/pkgconfig/ackermann_vehicle_description.pc
=========== ros-indigo-ackermann-vehicle-gazebo
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/ros-indigo-ackermann-vehicle-gazebo
/usr/share/doc/ros-indigo-ackermann-vehicle-gazebo/changelog.Debian.gz
/opt
/opt/ros
/opt/ros/indigo
/opt/ros/indigo/share
/opt/ros/indigo/share/ackermann_vehicle_gazebo
/opt/ros/indigo/share/ackermann_vehicle_gazebo/package.xml
/opt/ros/indigo/share/ackermann_vehicle_gazebo/cmake
/opt/ros/indigo/share/ackermann_vehicle_gazebo/cmake/ackermann_vehicle_gazeboConfig.cmake
/opt/ros/indigo/share/ackermann_vehicle_gazebo/cmake/ackermann_vehicle_gazeboConfig-version.cmake
/opt/ros/indigo/lib
/opt/ros/indigo/lib/pkgconfig
/opt/ros/indigo/lib/pkgconfig/ackermann_vehicle_gazebo.pc

**Comment by wunderkammer-laboratory** [comment]
> What is the relationship between the code in this git repository and the Ubuntu ros-indigo-ackermann-vehicle* packages?

This repository contains the files that constitute the ackermann_vehicle ROS packages.

>  It appears that the Ubuntu packages contain only package descriptions and cmake files - no URDF file, for example.

It looks as if there is a problem with the binary distribution. I'll investigate. In the meantime, you can download the source from the git repository to your own workspace, then build it.

**Comment by wunderkammer-laboratory** [comment]
> It appears that the Ubuntu packages contain only package descriptions and cmake files - no URDF
> file, for example.

Version 1.0.2 of ros-indigo-ackermann-vehicle* should install launch files and the URDF file correctly.

> Are there any examples/tutorials for using this code?

No, there are not.
