### ISSUE TITLE
Vehicle Not being Visualized Properly

### ISSUE THREAD

**Issue by ktiwari9** [wunderkammer-laboratory/ackermann_vehicle#4]
Hi there,
I want to visualize a car like robot in Gazebo besides a Husky A200 robot. I used your URDF file and my output looks somewhat like this;
![screenshot from 2015-08-19 13 50 46](https://cloud.githubusercontent.com/assets/5789469/9348997/2488bafa-467a-11e5-836e-f55cf7745ef5.png)

Is this how we expected the model to look like ? It looks very strange.
I have a feeling this cant be right since I see error in my terminal as you can also see in the screenshot. The error states:
[ERROR] [1439959835.329767525, 1.194000000]: No type element found for transmission joint_back_left_wheel_trans
[ERROR] [1439959835.329805168, 1.194000000]: No type element found for transmission joint_back_right_wheel_trans
[ERROR] [1439959835.329828395, 1.194000000]: No type element found for transmission joint_front_left_wheel_trans
[ERROR] [1439959835.329843516, 1.194000000]: No type element found for transmission joint_front_right_wheel_trans

**Comment by wunderkammer-laboratory** [comment]
The model needs controllers to be running in order to control the front wheel directions and the shock absorbers. Take a look at ackermann_vehicle_gazebo/launch/ackermann_vehicle.launch to see how to start the controllers. For an example of how the vehicle should look, run this in a shell window:

    roslaunch ackermann_vehicle_gazebo ackermann_vehicle.launch

**Comment by ktiwari9** [comment]
So as per your advise,
I tried using your package as it is n I get many more errors when I launch ackermann_vehicle.launch
[ERROR] [1440055936.633662413, 0.417000000]: Could not load controller 'right_front_shock_ctrlr' because controller type 'effort_controllers/JointPositionController' does not exist.
[ERROR] [1440055936.633698778, 0.417000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [WallTime: 1440055937.634107] [1.413000] Failed to load right_front_shock_ctrlr
[ERROR] [1440055937.636593663, 1.415000000]: Could not load controller 'right_front_axle_ctrlr' because controller type 'effort_controllers/JointVelocityController' does not exist.
[ERROR] [1440055937.636634379, 1.415000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [WallTime: 1440055938.637792] [2.417000] Failed to load right_front_axle_ctrlr
[ERROR] [1440055938.639779462, 2.419000000]: Could not load controller 'right_rear_shock_ctrlr' because controller type 'effort_controllers/JointPositionController' does not exist.
[ERROR] [1440055938.639814786, 2.419000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [WallTime: 1440055939.640969] [3.419000] Failed to load right_rear_shock_ctrlr
[ERROR] [1440055939.644334220, 3.422000000]: Could not load controller 'joint_state_ctrlr' because controller type 'joint_state_controller/JointStateController' does not exist.
[ERROR] [1440055939.644365937, 3.422000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [WallTime: 1440055940.645390] [4.421000] Failed to load joint_state_ctrlr
[ERROR] [1440055940.648273947, 4.424000000]: Could not load controller 'right_steering_ctrlr' because controller type 'effort_controllers/JointPositionController' does not exist.
[ERROR] [1440055940.648301249, 4.424000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [WallTime: 1440055941.649441] [5.424000] Failed to load right_steering_ctrlr
[ERROR] [1440055941.651863072, 5.427000000]: Could not load controller 'right_rear_axle_ctrlr' because controller type 'effort_controllers/JointVelocityController' does not exist.
[ERROR] [1440055941.651901834, 5.427000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [WallTime: 1440055942.652907] [6.427000] Failed to load right_rear_axle_ctrlr
[ERROR] [1440055942.654957723, 6.429000000]: Could not load controller 'left_front_shock_ctrlr' because controller type 'effort_controllers/JointPositionController' does not exist.
[ERROR] [1440055942.654986218, 6.429000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [WallTime: 1440055943.656155] [7.428000] Failed to load left_front_shock_ctrlr
[ERROR] [1440055943.658065510, 7.430000000]: Could not load controller 'left_rear_axle_ctrlr' because controller type 'effort_controllers/JointVelocityController' does not exist.
[ERROR] [1440055943.658095620, 7.430000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [WallTime: 1440055944.658540] [8.429000] Failed to load left_rear_axle_ctrlr
[ERROR] [1440055944.660628802, 8.431000000]: Could not load controller 'left_steering_ctrlr' because controller type 'effort_controllers/JointPositionController' does not exist.
[ERROR] [1440055944.660672951, 8.431000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
^C[ackermann_vehicle/ackermann_controller-6] killing on exit
[ackermann_vehicle/controller_spawner-5] killing on exit
[ackermann_vehicle/gazebo_gui-3] killing on exit
[ackermann_vehicle/gazebo-2] killing on exit
[ackermann_vehicle/vehicle_state_publisher-1] killing on exit
[WARN] [WallTime: 1440055945.624449] [8.767000] The specified list of shock absorbers is invalid. No shock absorbers will be used.


It is complaining about controllers not found. I did sudo apt-get install ros-hydro-ackermann_msgs
Is there any other package I need to install ?

**Comment by ktiwari9** [comment]
Also when I visualize this RViZ and add a robot model, I can readily see my Husky A200 but I do not see the Ackermann Vehicle. Do I need to change something in the launch file robot_description part ?

**Comment by wunderkammer-laboratory** [comment]
> I did sudo apt-get install ros-hydro-ackermann_msg. Is there any other package I need to install ?

It looks as if you need ros-hydro-ros-controllers.

>  I can readily see my Husky A200 but I do not see the Ackermann Vehicle.

You should be able to see the Ackermann vehicle in RViz if you do the following:

    roslaunch ackermann_vehicle_description ackermann_vehicle_rviz.launch

To view the Husky and the Ackermann vehicle together, modify your RViz launch file so that it starts the same nodes that ackermann_vehicle_description/launch/ackermann_vehicle_rviz.launch does.

**Comment by wunderkammer-laboratory** [comment]
In RViz, I view the Ackermann vehicle by setting the global frame to base_link. To view a Husky and the Ackermann vehicle, you will need a node that broadcasts transforms from a global frame, such as odom, to the base links of the Husky and the Ackermann vehicle.

**Comment by ktiwari9** [comment]
Here is my launch file:
<launch>

	
	 
  <arg name="paused" default="true"/>
  <arg name="use_sim_time" default="true"/>
  <arg name="extra_gazebo_args" default=""/>
  <arg name="gui" default="true"/>
  <arg name="headless" default="false"/>
  <arg name="debug" default="false"/>
  <arg name="physics" default="ode"/>
  <arg name="verbose" default="false"/>
  <arg name="throttled" default="false"/>
  <arg name="config" default="robot" />
  <arg name="robot_name" default="-x -5 -y 1 -z 0" />
  
  <arg name="init_pose" default="Robot1" />	
  <arg name="world_name" default="worlds/empty.world"/> 
  <arg name="cmd_vel_topic" default="/husky/cmd_vel" />
  <arg name="odom_topic" default="odom" />
  <arg name="namespace" default="ackermann_vehicle"/>



  
  <group if="$(arg use_sim_time)">
    <param name="/use_sim_time" value="true" />
  </group>

  
  <arg unless="$(arg paused)" name="command_arg1" value=""/>
  <arg     if="$(arg paused)" name="command_arg1" value="-u"/>
  <arg unless="$(arg headless)" name="command_arg2" value=""/>
  <arg     if="$(arg headless)" name="command_arg2" value="-r"/>
  <arg unless="$(arg verbose)" name="command_arg3" value=""/>
  <arg     if="$(arg verbose)" name="command_arg3" value="--verbose"/>
  <arg unless="$(arg debug)" name="script_type" value="gzserver"/>
  <arg     if="$(arg debug)" name="script_type" value="debug"/>

  
  <node name="gazebo" pkg="gazebo_ros" type="$(arg script_type)" respawn="false" output="screen"
	args="$(arg command_arg1) $(arg command_arg2) $(arg command_arg3) -e $(arg physics) $(arg extra_gazebo_args) $(arg world_name)" />
	
  
  <group if="$(arg gui)">
    <node name="gazebo_gui" pkg="gazebo_ros" type="gzclient" respawn="false" output="screen"/>
  </group>



    
    <param name="robot_description" command="$(find xacro)/xacro.py $(find husky_description)/urdf/base.urdf.xacro" />

    
    <node name="spawn_husky_model" pkg="gazebo_ros" type="spawn_model" args="$(arg init_pose) -unpause -urdf -param robot_description -model $(arg robot_name)" output="screen" />

    <node pkg="robot_state_publisher" type="robot_state_publisher" name="robot_state_publisher">
        <param name="publish_frequency" type="double" value="30.0" />
    </node>


	
	<node pkg="gazebo_husky" type="obs_husky" name="obs_husky" output="screen" >
		<param name="min_x" value="-0.010"/>
		<param name="max_x" value="0.010"/>
		<param name="min_y" value="-0.010"/>
		<param name="max_y" value="0.010"/> 
	</node>


	
	<include file="$(find gazebo_husky)/launch/ackermann_vehicle.launch">
    <arg name="namespace" value="$(arg namespace)"/>
  </include>
  
	<include file ="$(find gazebo_husky)/launch/ackermann_vehicle_rviz.launch"/>

	
	<node pkg="tf" type="static_transform_publisher" name="link1_broadcaster" args="0 0 0 0 0 0 /base_link /map 100"/>
   <node pkg="tf" type="static_transform_publisher" name="link2_broadcaster" args="0 0 0 0 0 0 /base_link /odom 100"/>


   <node pkg="frontier_exploration" type="explore_client" name="explore_client" output="screen"/>


   
  <node pkg="frontier_exploration" type="explore_server" name="explore_server" output="screen">
    <param name="frequency" value="1.0"/>
    
    <param name="goal_aliasing" value="0.2"/>
    <rosparam file="$(find husky_navigation)/config/costmap_common.yaml" command="load" ns="explore_costmap" />
    <rosparam file="$(find husky_navigation)/config/costmap_exploration.yaml" command="load" ns="explore_costmap" />
  </node>

  
  <include file ="$(find husky_navigation)/launch/gmapping.launch"/> 

  

  <include file ="$(find husky_navigation)/launch/move_base.launch"/>

   	
	<node name="RVIZ" pkg="rviz" type="rviz" args=" -d $(find gazebo_husky)/rviz_sim/husky_auto_nav.rviz" />
	

  
</launch>


In both RViz and Gazebo I only see my Husky. In your ackermann_vehicle.launch I just commented the part where you create an empty because I already have a world with husky. Am I doing something wrong here ? When I run just your package I can see the robot in both RViz and Gazebo with no errors. You were that I was missing ros-controllers package.

**Comment by ktiwari9** [comment]
Here is my launch file http://pastebin.ca/3118965
When I run your package separately I can see the robot properly in both RViZ And Gazebo but when I run my launch file I cannot see the Ackermann Vehicle but only my Husky.
Any suggestions as to what is wrong with my launch file ?

P.S. You were right that I was missing ros-controllers so when I run just your package everything is fine.

**Comment by wunderkammer-laboratory** [comment]
> Any suggestions as to what is wrong with my launch file ?

I think the problem involves namespaces. The Ackermann vehicle's robot_description should be in the ackermann_vehicle namespace, and the Husky's robot_description should be in some other namespace. In RViz, make certain that the TF Prefix attributes of the two RobotModel displays are set to the appropriate namespaces.

I have never displayed more than one robot at a time in RViz. Consider searching answers.ros.org for suggestions concerning displaying multiple robots.

**Comment by wunderkammer-laboratory** [comment]
Do you mind if I close this issue?
