### ISSUE TITLE
Way Point Planner for Ackermann Vehicle

### ISSUE THREAD

**Issue by ktiwari9** [wunderkammer-laboratory/ackermann_vehicle#5]
I want to move the Ackermann Vehicle from Point A to B via simple way points. How can I do this ?
Please advise.

**Comment by wunderkammer-laboratory** [comment]
The vehicle is controlled by ackermann_msgs/AckermannDriveStamped messages received from the ackermann_cmd topic, similar to how holonomic robots are controlled by geometry_msgs/Twist messages received from cmd_vel. You could use the ROS navigation package, then write a node that subscribes to cmd_vel. For each message received from cmd_vel, the node would translate the field values into an AckermannDriveStamped message, then publish the AckermannDriveStamped message to ackermann_cmd. Here are some links related to using ROS navigation with an Ackermann vehicle:

    http://answers.ros.org/question/9059/how-can-i-use-the-navigation-stack-on-a-carlike-robot/
    http://wiki.ros.org/Ackermann%20Group

**Comment by ktiwari9** [comment]
Following your comments I wrote a simple code as uploaded here http://pastebin.ca/3118971
But I do not see the robot move. Am I doing something wrong in this code ?

**Comment by ktiwari9** [comment]
My aim is to just move the ackermann vehicle in a straight line from 4,1 to -4,1. Is there a simple function u can help me write to realize this straight line motion ? I do not have any obstacles etc to take care of. Just a simple straight line motion from known start and end points and tossing a coin to choose when to move. For instance if coin says head move or else stay where it is.

**Comment by wunderkammer-laboratory** [comment]
> Following your comments I wrote a simple code as uploaded here http://pastebin.ca/3118971
> But I do not see the robot move. Am I doing something wrong in this code ? 

Use "rostopic echo" to make certain that messages are being published to the ackermann_cmd topic. Make certain that the "speed" field is nonzero. Make certain that the ackermann_cmd topic being published to and being subscribed to are in the same namespace. In http://pastebin.ca/3118971, I could not find any code that calls setVehicleSpeed(). Is setVehicleSpeed() called somewhere else?

**Comment by wunderkammer-laboratory** [comment]
> My aim is to just move the ackermann vehicle in a straight line from 4,1 to -4,1. Is there a simple
> function u can help me write to realize this straight line motion ?

Since the ackermann_controller node does not publish odometry data, there is no simple way to control the vehicle's position. I suggest adding the Gazebo P3D plugin to the vehicle's URDF file. That will publish the vehicle's pose in world space. You could then write a node that subscribes to the messages. In the subscriber callback, compare the reported pose with the desired pose. Set the steering position to point toward the goal, set the speed to a value proportional to the distance to the goal, then publish an AckermannDriveStamped message.

**Comment by wunderkammer-laboratory** [comment]
Do you mind if I close this issue?

**Comment by ktiwari9** [comment]
Sure thing :)
