### ISSUE TITLE
Having error with roslaunch ackermann_vehicle_gazebo

### ISSUE THREAD

**Issue by mos127** [wunderkammer-laboratory/ackermann_vehicle#6]
Hi there,

This error occurs when I want to launch  ackermann_vehicle_gazebo:

[ackermann_vehicle/ackermann_controller-7] process has died [pid 11234, exit code 1, cmd /home/mos/catkin_workspace/src/ackermann_vehicle/ackermann_vehicle_gazebo/scripts/ackermann_controller __name:=ackermann_controller __log:=/home/mos/.ros/log/78b08e4a-567f-11e5-bc09-000c29367276/ackermann_vehicle-ackermann_controller-7.log].
log file: /home/mos/.ros/log/78b08e4a-567f-11e5-bc09-000c29367276/ackermann_vehicle-ackermann_controller-7*.log

What is this error for? Thanks!

**Comment by wunderkammer-laboratory** [comment]
How are you launching the launch file? All you should have to do is:

    roslaunch ackermann_vehicle_gazebo ackermann_vehicle.launch

If this doesn't work, make sure that all the run_depend packages listed in ackermann_vehicle_gazebo/package.xml are installed. If an error still occurs, please post all the terminal output, i.e. the text displayed after running roslaunch, including error messages.

**Comment by mos127** [comment]
I checked all the dependencies and it seems everything is installed
I should also mention that I'm using ROS indigo version. I can see the robot in the gazebo and I can control it by sending command to the topics like /ackermann_vehicle/left_front_axle_ctrlr/command

 The same error still occurs:

mos@ubuntu:~$ roslaunch ackermann_vehicle_gazebo ackermann_vehicle.launch
... logging to /home/mos/.ros/log/2b4cad50-568e-11e5-8638-000c29367276/roslaunch-ubuntu-39966.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:58731/

SUMMARY
========

PARAMETERS
 * /ackermann_vehicle/ackermann_controller/cmd_timeout: 0.5
 * /ackermann_vehicle/ackermann_controller/left_front_wheel/axle_controller_name: left_front_axle_c...
 * /ackermann_vehicle/ackermann_controller/left_front_wheel/diameter: 0.14605
 * /ackermann_vehicle/ackermann_controller/left_front_wheel/steering_controller_name: left_steering_ctrlr
 * /ackermann_vehicle/ackermann_controller/left_front_wheel/steering_link_name: left_front_wheel
 * /ackermann_vehicle/ackermann_controller/left_rear_wheel/axle_controller_name: left_rear_axle_ctrlr
 * /ackermann_vehicle/ackermann_controller/left_rear_wheel/diameter: 0.14605
 * /ackermann_vehicle/ackermann_controller/left_rear_wheel/link_name: left_rear_wheel
 * /ackermann_vehicle/ackermann_controller/right_front_wheel/axle_controller_name: right_front_axle_...
 * /ackermann_vehicle/ackermann_controller/right_front_wheel/diameter: 0.14605
 * /ackermann_vehicle/ackermann_controller/right_front_wheel/steering_controller_name: right_steering_ctrlr
 * /ackermann_vehicle/ackermann_controller/right_front_wheel/steering_link_name: right_front_wheel
 * /ackermann_vehicle/ackermann_controller/right_rear_wheel/axle_controller_name: right_rear_axle_c...
 * /ackermann_vehicle/ackermann_controller/right_rear_wheel/diameter: 0.14605
 * /ackermann_vehicle/ackermann_controller/right_rear_wheel/link_name: right_rear_wheel
 * /ackermann_vehicle/ackermann_controller/shock_absorbers: [{'controller_nam...
 * /ackermann_vehicle/robot_description: <?xml version="1....
 * /ackermann_vehicle/vehicle_state_publisher/publish_frequency: 30.0
 * /rosdistro: indigo
 * /rosversion: 1.11.13
 * /use_sim_time: True

NODES
  /ackermann_vehicle/
    ackermann_controller (ackermann_vehicle_gazebo/ackermann_controller)
    controller_spawner (controller_manager/spawner)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    spawn_vehicle (gazebo_ros/spawn_model)
    vehicle_state_publisher (robot_state_publisher/robot_state_publisher)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[ackermann_vehicle/vehicle_state_publisher-1]: started with pid [39987]
process[ackermann_vehicle/gazebo-2]: started with pid [40020]
Gazebo multi-robot simulator, version 2.2.5
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

process[ackermann_vehicle/gazebo_gui-3]: started with pid [40029]
Gazebo multi-robot simulator, version 2.2.5
Copyright (C) 2012-2014 Open Source Robotics Foundation.
Released under the Apache 2 License.
http://gazebosim.org

process[ackermann_vehicle/spawn_vehicle-4]: started with pid [40036]
[ INFO] [1441762310.419767411]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1441762310.426433720]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
Msg Waiting for master
Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.244.129
Msg Waiting for master
Msg Connected to gazebo master @ http://127.0.0.1:11345
Msg Publicized address: 192.168.244.129
process[ackermann_vehicle/controller_spawner-5]: started with pid [40066]
process[ackermann_vehicle/ackermann_controller-6]: started with pid [40068]
Error [InsertModelWidget.cc:233] Missing model.config for model "/home/mos/.gazebo/models/sancaground"
Error [InsertModelWidget.cc:233] Missing model.config for model "/home/mos/.gazebo/models/sancasun"
[ INFO] [1441762312.631163509, 0.813000000]: Loading gazebo_ros_control plugin
[ INFO] [1441762312.632161016, 0.813000000]: Starting gazebo_ros_control plugin in namespace: /ackermann_vehicle/
[ INFO] [1441762312.633614642, 0.813000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [/ackermann_vehicle/robot_description] on the ROS param server.
Traceback (most recent call last):
  File "/home/mos/catkin_workspace/src/ackermann_vehicle/ackermann_vehicle_gazebo/scripts/ackermann_controller", line 123, in <module>
    from ackermann_msgs.msg import AckermannDriveStamped
ImportError: No module named ackermann_msgs.msg
[ackermann_vehicle/spawn_vehicle-4] process has finished cleanly
log file: /home/mos/.ros/log/2b4cad50-568e-11e5-8638-000c29367276/ackermann_vehicle-spawn_vehicle-4*.log
[ackermann_vehicle/ackermann_controller-6] process has died [pid 40068, exit code 1, cmd /home/mos/catkin_workspace/src/ackermann_vehicle/ackermann_vehicle_gazebo/scripts/ackermann_controller __name:=ackermann_controller __log:=/home/mos/.ros/log/2b4cad50-568e-11e5-8638-000c29367276/ackermann_vehicle-ackermann_controller-6.log].
log file: /home/mos/.ros/log/2b4cad50-568e-11e5-8638-000c29367276/ackermann_vehicle-ackermann_controller-6*.log
[ INFO] [1441762313.068623113, 0.813000000]: Loaded gazebo_ros_control.

**Comment by wunderkammer-laboratory** [comment]
File "/home/mos/catkin_workspace/src/ackermann_vehicle/ackermann_vehicle_gazebo/scripts/ackermann_controller", line 123, in
    from ackermann_msgs.msg import AckermannDriveStamped
    ImportError: No module named ackermann_msgs.msg

The script can't import AckermannDriveStamped. Make sure that ros-indigo-ackermann-msgs is installed.

**Comment by mos127** [comment]
Sorry I checked through rosdep and these two were not installed:
mos@ubuntu:~/catkin_workspace$ rosdep check ackermann_vehicle_gazebo
System dependencies have not been satisified:
apt	ros-indigo-ackermann-vehicle-description
apt	ros-indigo-ackermann-msgs

I installed them and now it works like a charm, Thanks so much!
